name: Arduino Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Arduino CLI
      - name: Install Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xvzf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/

      # Step 3: Add and install ESP32 core
      - name: Set up ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli config init
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/Heltec-Aaron-Lee/WiFi_Kit_series/refs/heads/master/package.json
          arduino-cli core install --additional-urls https://resource.heltec.cn/download/package_heltec_esp32_index.json Heltec-ESP32:esp32@3.0.2
          
      # Step 4: Install Arduino libraries
      - name: Install Arduino Libraries
        run: |
          arduino-cli lib install "AM2302-Sensor@1.4.0"
          arduino-cli lib install "Adafruit GFX Library@1.11.10"
          arduino-cli lib install "Adafruit BusIO@1.16.1"
          arduino-cli lib install "Heltec ESP32 Dev-Boards"

      # Step 5: Compile Arduino sketch
      - name: Compile Sketch
        run: |
          cp main/credentials_sample.h main/credentials.h
          make compile
