name: Arduino Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Schritt 2: Arduino CLI installieren
      - name: Install Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xvzf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/

      # Schritt 3: ESP32 Core URL hinzufügen und installieren
      - name: Set up ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli config init
          arduino-cli core install Heltec-ESP32:esp32@3.0.2 --additional-urls https://raw.githubusercontent.com/Heltec-Aaron-Lee/WiFi_Kit_series/refs/heads/master/package.json
          
      # Schritt 4: Arduino-Bibliotheken installieren
      - name: Install Arduino Libraries
        run: |
          arduino-cli lib install "AM2302-Sensor@1.4.0"
          arduino-cli lib install "Adafruit GFX Library@1.11.10"
          arduino-cli lib install "Adafruit BusIO@1.16.1"

      # Schritt 5: Kompilieren des Arduino Sketches
      - name: Compile Sketch
        run: arduino-cli compile --fqbn Heltec-esp32:esp32:heltec_wifi_lora_32 main/main.ino

      # Optional: Schritt 6: Hochladen auf das Gerät (wenn nötig, für Self-hosted Runner)
      # - name: Upload Sketch
      #   run: arduino-cli upload --fqbn Heltec-esp32:esp32:heltec_wifi_lora_32 --port /dev/ttyUSB0 <Pfad/zum/Sketch.ino>
